export { DashboardStats } from "./components/DashboardStats"
export { DepotStockChart } from "./components/DepotStockChart"
export { CategoryChart } from "./components/CategoryChart"
export { TopClients } from "./components/TopClients"
export { TopFournisseurs } from "./components/TopFournisseurs"
export { TopStockedArticles } from "./components/TopStockedArticles"
export { DepotsList } from "./components/DepotsList"
export { RecentArticles } from "./components/RecentArticles"
export { StatCard } from "./components/StatCard"
export {DashboardPage} from "./pages/DashboardPage"